#include <CeilingPinch/CeilingPinchUtils.h>
#include <RLGymSim_CPP/Utils/OBSBuilders/DefaultOBSPadded.h>

using namespace RLGSC;

START_CEILINGPINCH_OB_NS

//Autogenerated, inherits DefaultOBSPadded (Auto-generated comment)
class CeilingPinchObsBuilder: public DefaultOBSPadded{
};

END_CEILINGPINCH_NS
