#include <Utils/VoidUtils.h>

//Base namespace utils (Auto-generated comment)
#define CEILINGPINCH_NS CeilingPinch
#define START_CEILINGPINCH_NS START_VOID_SUB_NS(CEILINGPINCH_NS)
#define END_CEILINGPINCH_NS END_NS

//Sub namespaces start macros (Auto-generated comment)
#define START_CEILINGPINCH_REWARDS_NS START_VOID_SUB_NS(CEILINGPINCH_NS::Rewards)
#define START_CEILINGPINCH_STATES_NS START_VOID_SUB_NS(CEILINGPINCH_NS::States)
#define START_CEILINGPINCH_AP_NS START_VOID_SUB_NS(CEILINGPINCH_NS::AP)
#define START_CEILINGPINCH_OB_NS START_VOID_SUB_NS(CEILINGPINCH_NS::OB)

//Sub namespaces use macros (Auto-generated comment)
#define USE_CEILINGPINCH_REWARDS_NS USE_VOID_SUB_NS(CEILINGPINCH_NS::Rewards)
#define USE_CEILINGPINCH_STATES_NS USE_VOID_SUB_NS(CEILINGPINCH_NS::States)
#define USE_CEILINGPINCH_AP_NS USE_VOID_SUB_NS(CEILINGPINCH_NS::AP)
#define USE_CEILINGPINCH_OB_NS USE_VOID_SUB_NS(CEILINGPINCH_NS::OB)
