#include <WallPinch/WallPinchUtils.h>
#include <RLGymSim_CPP/Utils/OBSBuilders/DefaultOBSPadded.h>

using namespace RLGSC;

START_WALLPINCH_OB_NS

//Autogenerated, inherits DefaultOBSPadded (Auto-generated comment)
class WallPinchObsBuilder: public DefaultOBSPadded{
};

END_WALLPINCH_NS
