#include <DoubleTap/DoubleTapUtils.h>
#include <RLGymSim_CPP/Utils/OBSBuilders/DefaultOBSPadded.h>

using namespace RLGSC;

START_DOUBLETAP_OB_NS

//Autogenerated, inherits DefaultOBSPadded (Auto-generated comment)
class DoubleTapObsBuilder: public DefaultOBSPadded{
};

END_DOUBLETAP_NS
