#include <GroundPinch/GroundPinchUtils.h>
#include <RLGymSim_CPP/Utils/ActionParsers/DiscreteAction.h>

using namespace RLGSC;

START_GROUNDPINCH_AP_NS

//Autogenerated, inherits DiscreteAction (Auto-generated comment)
class GroundPinchActionParser: public DiscreteAction{
};

END_GROUNDPINCH_NS
