#include <WallPinch/WallPinchUtils.h>
#include <RLGymSim_CPP/Utils/ActionParsers/DiscreteAction.h>

using namespace RLGSC;

START_WALLPINCH_AP_NS

//Autogenerated, inherits DiscreteAction (Auto-generated comment)
class WallPinchActionParser: public DiscreteAction{
};

END_WALLPINCH_NS
