#include <Recovery/RecoveryUtils.h>
#include <RLGymSim_CPP/Utils/OBSBuilders/DefaultOBSPadded.h>

using namespace RLGSC;

START_RECOVERY_OB_NS

//Autogenerated, inherits DefaultOBSPadded (Auto-generated comment)
class RecoveryObsBuilder: public DefaultOBSPadded{
};

END_RECOVERY_NS
