#include <TeamPinch/TeamPinchUtils.h>
#include <RLGymSim_CPP/Utils/ActionParsers/DiscreteAction.h>

using namespace RLGSC;

START_TEAMPINCH_AP_NS

//Autogenerated, inherits DiscreteAction (Auto-generated comment)
class TeamPinchActionParser: public DiscreteAction{
};

END_TEAMPINCH_NS
