#include <Utils/VoidUtils.h>

//Base namespace utils (Auto-generated comment)
#define TEAMPINCH_NS TeamPinch
#define START_TEAMPINCH_NS START_VOID_SUB_NS(TEAMPINCH_NS)
#define END_TEAMPINCH_NS END_NS

//Sub namespaces start macros (Auto-generated comment)
#define START_TEAMPINCH_REWARDS_NS START_VOID_SUB_NS(TEAMPINCH_NS::Rewards)
#define START_TEAMPINCH_STATES_NS START_VOID_SUB_NS(TEAMPINCH_NS::States)
#define START_TEAMPINCH_AP_NS START_VOID_SUB_NS(TEAMPINCH_NS::AP)
#define START_TEAMPINCH_OB_NS START_VOID_SUB_NS(TEAMPINCH_NS::OB)

//Sub namespaces use macros (Auto-generated comment)
#define USE_TEAMPINCH_REWARDS_NS USE_VOID_SUB_NS(TEAMPINCH_NS::Rewards)
#define USE_TEAMPINCH_STATES_NS USE_VOID_SUB_NS(TEAMPINCH_NS::States)
#define USE_TEAMPINCH_AP_NS USE_VOID_SUB_NS(TEAMPINCH_NS::AP)
#define USE_TEAMPINCH_OB_NS USE_VOID_SUB_NS(TEAMPINCH_NS::OB)
