#include <Utils/VoidUtils.h>

//Base namespace utils (Auto-generated comment)
#define SELECTOR_NS Selector
#define START_SELECTOR_NS START_VOID_SUB_NS(SELECTOR_NS)
#define END_SELECTOR_NS END_NS

//Sub namespaces start macros (Auto-generated comment)
#define START_SELECTOR_REWARDS_NS START_VOID_SUB_NS(SELECTOR_NS::Rewards)
#define START_SELECTOR_STATES_NS START_VOID_SUB_NS(SELECTOR_NS::States)
#define START_SELECTOR_AP_NS START_VOID_SUB_NS(SELECTOR_NS::AP)
#define START_SELECTOR_OB_NS START_VOID_SUB_NS(SELECTOR_NS::OB)

//Sub namespaces use macros (Auto-generated comment)
#define USE_SELECTOR_REWARDS_NS USE_VOID_SUB_NS(SELECTOR_NS::Rewards)
#define USE_SELECTOR_STATES_NS USE_VOID_SUB_NS(SELECTOR_NS::States)
#define USE_SELECTOR_AP_NS USE_VOID_SUB_NS(SELECTOR_NS::AP)
#define USE_SELECTOR_OB_NS USE_VOID_SUB_NS(SELECTOR_NS::OB)
