#include <CeilingPinch/CeilingPinchUtils.h>
#include <RLGymSim_CPP/Utils/ActionParsers/DiscreteAction.h>

using namespace RLGSC;

START_CEILINGPINCH_AP_NS

//Autogenerated, inherits DiscreteAction (Auto-generated comment)
class CeilingPinchActionParser: public DiscreteAction{
};

END_CEILINGPINCH_NS
