#include <TeamPinch/TeamPinchUtils.h>
#include <RLGymSim_CPP/Utils/OBSBuilders/DefaultOBSPadded.h>

using namespace RLGSC;

START_TEAMPINCH_OB_NS

//Autogenerated, inherits DefaultOBSPadded (Auto-generated comment)
class TeamPinchObsBuilder: public DefaultOBSPadded{
};

END_TEAMPINCH_NS
