#include <GroundPinch/GroundPinchUtils.h>
#include <RLGymSim_CPP/Utils/OBSBuilders/DefaultOBSPadded.h>

using namespace RLGSC;

START_GROUNDPINCH_OB_NS

//Autogenerated, inherits DefaultOBSPadded (Auto-generated comment)
class GroundPinchObsBuilder: public DefaultOBSPadded{
};

END_GROUNDPINCH_NS
