#include <Utils/VoidUtils.h>

//Base namespace utils (Auto-generated comment)
#define RECOVERY_NS Recovery
#define START_RECOVERY_NS START_VOID_SUB_NS(RECOVERY_NS)
#define END_RECOVERY_NS END_NS

//Sub namespaces start macros (Auto-generated comment)
#define START_RECOVERY_REWARDS_NS START_VOID_SUB_NS(RECOVERY_NS::Rewards)
#define START_RECOVERY_STATES_NS START_VOID_SUB_NS(RECOVERY_NS::States)
#define START_RECOVERY_AP_NS START_VOID_SUB_NS(RECOVERY_NS::AP)
#define START_RECOVERY_OB_NS START_VOID_SUB_NS(RECOVERY_NS::OB)

//Sub namespaces use macros (Auto-generated comment)
#define USE_RECOVERY_REWARDS_NS USE_VOID_SUB_NS(RECOVERY_NS::Rewards)
#define USE_RECOVERY_STATES_NS USE_VOID_SUB_NS(RECOVERY_NS::States)
#define USE_RECOVERY_AP_NS USE_VOID_SUB_NS(RECOVERY_NS::AP)
#define USE_RECOVERY_OB_NS USE_VOID_SUB_NS(RECOVERY_NS::OB)