#include <Utils/VoidUtils.h>

//Base namespace utils (Auto-generated comment)
#define GROUNDPINCH_NS GroundPinch
#define START_GROUNDPINCH_NS START_VOID_SUB_NS(GROUNDPINCH_NS)
#define END_GROUNDPINCH_NS END_NS

//Sub namespaces start macros (Auto-generated comment)
#define START_GROUNDPINCH_REWARDS_NS START_VOID_SUB_NS(GROUNDPINCH_NS::Rewards)
#define START_GROUNDPINCH_STATES_NS START_VOID_SUB_NS(GROUNDPINCH_NS::States)
#define START_GROUNDPINCH_AP_NS START_VOID_SUB_NS(GROUNDPINCH_NS::AP)
#define START_GROUNDPINCH_OB_NS START_VOID_SUB_NS(GROUNDPINCH_NS::OB)

//Sub namespaces use macros (Auto-generated comment)
#define USE_GROUNDPINCH_REWARDS_NS USE_VOID_SUB_NS(GROUNDPINCH_NS::Rewards)
#define USE_GROUNDPINCH_STATES_NS USE_VOID_SUB_NS(GROUNDPINCH_NS::States)
#define USE_GROUNDPINCH_AP_NS USE_VOID_SUB_NS(GROUNDPINCH_NS::AP)
#define USE_GROUNDPINCH_OB_NS USE_VOID_SUB_NS(GROUNDPINCH_NS::OB)
