#include <Recovery/RecoveryUtils.h>
#include <RLGymSim_CPP/Utils/ActionParsers/DiscreteAction.h>

using namespace RLGSC;

START_RECOVERY_AP_NS

//Autogenerated, inherits DiscreteAction (Auto-generated comment)
class RecoveryActionParser: public DiscreteAction{
public:
	std::vector<Action> actions;
	RecoveryActionParser();

	virtual ActionSet ParseActions(const Input& actionsData, const GameState& gameState) {
		ActionSet result;
		for (int idx : actionsData)
			result.push_back(actions[idx]);
		return result;
	}

	virtual int GetActionAmount() {
		return actions.size();
	}
};

END_RECOVERY_NS
