#include <DoubleTap/DoubleTapUtils.h>
#include <RLGymSim_CPP/Utils/ActionParsers/DiscreteAction.h>

using namespace RLGSC;

START_DOUBLETAP_AP_NS

//Autogenerated, inherits DiscreteAction (Auto-generated comment)
class DoubleTapActionParser: public DiscreteAction{
};

END_DOUBLETAP_NS
